// GENERATED — `npm run gen:component-color-fields`. Do not hand-edit.
// See scripts/gen-component-color-fields.ts for what this is and why.

import type { PreviewColorField } from './previewColorFields'

/** Component catalogue key → the PreviewTokens color fields its own
 *  specimen (docs/specimens.tsx) actually reads, transitively through
 *  any shared helper it calls. A key absent from this map has no scoped
 *  color data yet — its agent context falls back to the full palette. */
export const COMPONENT_COLOR_FIELDS: Record<string, PreviewColorField[]> = {
  "Accordion": ['surface', 'neutralFill', 'neutralText', 'borderDefault', 'fgMuted'],
  "AlertBanner": ['brandSolid', 'neutralText', 'errorColor', 'fgMuted', 'successColor', 'warningColor', 'infoColor'],
  "AppStoreBadge": ['neutralText'],
  "AspectRatio": ['brandSolid', 'brandText', 'neutralText', 'borderDefault'],
  "Avatar": ['brandSolid', 'brandText', 'neutralText'],
  "Badge": ['brandSolid', 'onBrand', 'neutralFill', 'neutralText', 'errorColor', 'fgMuted', 'successColor', 'warningColor', 'infoColor'],
  "Breadcrumb": ['neutralText', 'fgMuted', 'placeholderText'],
  "Button": ['brandSolid', 'brandText', 'onBrand', 'neutralText', 'errorColor', 'disabledBg', 'disabledText', 'successColor', 'warningColor', 'infoColor', 'ghostBrandHover', 'ghostBrandPressed'],
  "ButtonGroup": ['neutralFill', 'neutralText', 'border'],
  "Card": ['brandText', 'neutralText', 'borderDefault', 'fgMuted'],
  "Checkbox": ['brandSolid', 'onBrand', 'neutralText', 'disabledBg', 'disabledText', 'border', 'inputSurface'],
  "CheckboxGroup": ['brandSolid', 'onBrand', 'neutralText', 'border', 'fgMuted', 'inputSurface'],
  "Chip": ['brandSolid', 'brandText', 'neutralText', 'border', 'selectedSurface'],
  "CloseButton": ['brandSolid', 'neutralText', 'fgMuted', 'ghostNeutralHover', 'ghostNeutralPressed'],
  "Combobox": ['brandSolid', 'brandText', 'neutralText', 'border', 'borderDefault', 'fgMuted', 'placeholderText', 'inputSurface'],
  "Command": ['neutralFill', 'neutralText', 'borderDefault', 'fgMuted', 'placeholderText'],
  "ContextMenu": ['neutralText', 'errorColor', 'borderDefault', 'placeholderText', 'ghostNeutralHover'],
  "Divider": ['borderDefault'],
  "DropdownMenu": ['surface', 'neutralFill', 'neutralText', 'errorColor', 'border', 'borderDefault', 'fgMuted', 'placeholderText', 'ghostNeutralHover'],
  "Dropzone": ['brandSolid', 'brandText', 'neutralText', 'errorColor', 'border', 'fgMuted'],
  "FABButton": ['brandSolid', 'onBrand'],
  "Field": ['neutralText', 'errorColor', 'border', 'fgMuted', 'inputSurface'],
  "FileFormat": ['surface', 'neutralFill', 'border'],
  "FileUpload": ['surface', 'brandSolid', 'brandText', 'neutralFill', 'neutralText', 'border', 'borderDefault', 'fgMuted'],
  "InfoTooltip": ['surface', 'neutralText', 'fgMuted'],
  "InlineAlert": ['brandSolid', 'neutralText', 'errorColor', 'fgMuted', 'successColor', 'warningColor', 'infoColor'],
  "Input": ['brandSolid', 'neutralText', 'errorColor', 'disabledBg', 'disabledText', 'border', 'fgMuted', 'placeholderText', 'inputSurface', 'borderHover', 'borderCritical'],
  "InputGroup": ['brandText', 'neutralFill', 'neutralText', 'border', 'fgMuted', 'inputSurface'],
  "InputOTP": ['brandSolid', 'neutralText', 'border', 'inputSurface', 'borderCritical'],
  "InputStepper": ['neutralText', 'border', 'fgMuted', 'inputSurface'],
  "InputTag": ['brandSolid', 'brandText', 'neutralText', 'border', 'placeholderText', 'inputSurface'],
  "Label": ['neutralText', 'errorColor'],
  "Modal": ['onBrand', 'neutralText', 'errorColor', 'border', 'borderDefault', 'fgMuted'],
  "Navbar": ['surface', 'brandSolid', 'brandText', 'neutralFill', 'neutralText', 'borderDefault', 'fgMuted'],
  "Pagination": ['brandSolid', 'onBrand', 'neutralText', 'placeholderText'],
  "PasswordStrength": ['neutralFill', 'neutralText', 'errorColor', 'border', 'fgMuted', 'successColor', 'warningColor', 'inputSurface'],
  "Popover": ['surface', 'brandSolid', 'onBrand', 'neutralFill', 'neutralText', 'border', 'borderDefault', 'fgMuted'],
  "Progress": ['brandSolid', 'neutralFill', 'neutralText', 'fgMuted'],
  "Radio": ['brandSolid', 'neutralText', 'disabledBg', 'disabledText', 'border', 'inputSurface'],
  "RadioGroup": ['brandSolid', 'neutralText', 'disabledBg', 'disabledText', 'border', 'fgMuted', 'inputSurface'],
  "Rating": ['neutralFill', 'neutralText', 'fgMuted', 'warningColor'],
  "ScrollArea": ['surface', 'neutralFill', 'neutralText', 'borderDefault'],
  "SegmentedControl": ['neutralFill', 'neutralText', 'fgMuted', 'inputSurface'],
  "Select": ['neutralText', 'disabledBg', 'disabledText', 'border', 'fgMuted', 'placeholderText', 'inputSurface', 'borderHover', 'borderCritical'],
  "Sidebar": ['surface', 'brandSolid', 'brandText', 'neutralFill', 'neutralText', 'borderDefault'],
  "Slider": ['brandSolid', 'neutralFill', 'neutralText', 'fgMuted'],
  "SocialLoginButton": ['surface', 'neutralFill', 'neutralText', 'border'],
  "Spinner": ['brandSolid', 'neutralFill'],
  "StatusBadge": ['surface', 'neutralFill', 'neutralText', 'borderDefault'],
  "Stepper": ['brandSolid', 'brandText', 'onBrand', 'neutralFill', 'neutralText', 'fgMuted'],
  "SwitchGroup": ['brandSolid', 'onBrand', 'neutralFill', 'neutralText', 'fgMuted', 'inputSurface'],
  "TabMenu": ['brandText', 'neutralText', 'fgMuted', 'selectedSurface'],
  "Tabs": ['brandSolid', 'brandText', 'neutralText', 'borderDefault', 'fgMuted'],
  "Textarea": ['neutralText', 'errorColor', 'disabledBg', 'disabledText', 'border', 'fgMuted', 'placeholderText', 'inputSurface', 'borderHover', 'borderCritical'],
  "TextLink": ['disabledText', 'linkText', 'linkHover'],
  "Toast": ['surface', 'brandSolid', 'neutralText', 'errorColor', 'successColor', 'warningColor', 'infoColor'],
  "Toggle": ['brandSolid', 'onBrand', 'neutralFill', 'neutralText', 'disabledBg', 'disabledText', 'inputSurface'],
  "Tooltip": ['surface', 'neutralText'],
}
