// GENERATED — `npm run gen:component-color-fields`. Do not hand-edit.
// See scripts/gen-component-color-fields.ts for what this is and why.

import type { PreviewColorField } from './previewColorFields'

/** Component catalogue key → the PreviewTokens color fields its own
 *  specimen (docs/specimens.tsx) actually reads, transitively through
 *  any shared helper it calls. A key absent from this map has no scoped
 *  color data yet — its agent context falls back to the full palette. */
export const COMPONENT_COLOR_FIELDS: Record<string, PreviewColorField[]> = {
  "Accordion": ['surface', 'neutralText', 'borderDefault', 'fgMuted'],
  "AlertBanner": ['brandSolid', 'neutralText', 'errorColor', 'fgMuted', 'successColor', 'warningColor', 'infoColor'],
  "AppStoreBadge": ['neutralText'],
  "AspectRatio": ['brandSolid', 'brandText', 'neutralText', 'borderDefault'],
  "Avatar": ['brandSolid', 'brandText', 'neutralText'],
  "Badge": ['brandSolid', 'onBrand', 'neutralFill', 'neutralText', 'errorColor', 'fgMuted', 'successColor', 'warningColor', 'infoColor'],
  "Breadcrumb": ['neutralText', 'fgMuted', 'placeholderText'],
  "Button": ['brandSolid', 'brandText', 'onBrand', 'neutralText', 'errorColor', 'disabledBg', 'disabledText', 'successColor', 'warningColor', 'infoColor'],
  "ButtonGroup": ['surface', 'neutralFill', 'neutralText', 'border'],
  "Card": ['brandText', 'neutralText', 'borderDefault', 'fgMuted'],
  "Checkbox": ['surface', 'brandSolid', 'onBrand', 'neutralText', 'disabledBg', 'disabledText', 'border'],
  "CheckboxGroup": ['surface', 'brandSolid', 'onBrand', 'neutralText', 'border', 'fgMuted'],
  "Chip": ['surface', 'brandSolid', 'brandText', 'neutralText', 'border'],
  "CloseButton": ['brandSolid', 'neutralText', 'fgMuted'],
  "Combobox": ['surface', 'brandSolid', 'brandText', 'neutralText', 'border', 'borderDefault', 'fgMuted', 'placeholderText'],
  "Command": ['surface', 'neutralFill', 'neutralText', 'borderDefault', 'fgMuted', 'placeholderText'],
  "ContextMenu": ['surface', 'neutralFill', 'neutralText', 'errorColor', 'borderDefault', 'placeholderText'],
  "Divider": ['borderDefault'],
  "DropdownMenu": ['surface', 'neutralFill', 'neutralText', 'errorColor', 'border', 'borderDefault', 'fgMuted', 'placeholderText'],
  "Dropzone": ['surface', 'brandSolid', 'brandText', 'neutralText', 'errorColor', 'border', 'fgMuted'],
  "FABButton": ['brandSolid', 'onBrand'],
  "Field": ['surface', 'neutralText', 'errorColor', 'border', 'fgMuted', 'placeholderText'],
  "FileFormat": ['surface', 'border'],
  "FileUpload": ['surface', 'brandSolid', 'brandText', 'neutralFill', 'neutralText', 'border', 'borderDefault', 'fgMuted'],
  "InfoTooltip": ['surface', 'neutralText', 'fgMuted'],
  "InlineAlert": ['brandSolid', 'neutralText', 'errorColor', 'fgMuted', 'successColor', 'warningColor', 'infoColor'],
  "Input": ['brandSolid', 'neutralText', 'errorColor', 'disabledBg', 'disabledText', 'border', 'fgMuted', 'placeholderText'],
  "InputGroup": ['brandText', 'neutralFill', 'neutralText', 'border', 'fgMuted'],
  "InputOTP": ['surface', 'brandSolid', 'neutralText', 'errorColor', 'border'],
  "InputStepper": ['surface', 'neutralText', 'border', 'fgMuted'],
  "InputTag": ['surface', 'brandSolid', 'brandText', 'neutralText', 'border', 'placeholderText'],
  "Label": ['neutralText', 'errorColor'],
  "Modal": ['surface', 'onBrand', 'neutralText', 'errorColor', 'border', 'borderDefault', 'fgMuted'],
  "Navbar": ['surface', 'brandSolid', 'brandText', 'neutralText', 'borderDefault', 'fgMuted'],
  "Pagination": ['brandSolid', 'onBrand', 'neutralText', 'placeholderText'],
  "PasswordStrength": ['neutralFill', 'neutralText', 'errorColor', 'border', 'fgMuted', 'successColor', 'warningColor'],
  "Popover": ['surface', 'brandSolid', 'onBrand', 'neutralText', 'border', 'borderDefault', 'fgMuted'],
  "Progress": ['brandSolid', 'neutralFill', 'neutralText', 'fgMuted'],
  "Radio": ['surface', 'brandSolid', 'neutralText', 'disabledBg', 'disabledText', 'border'],
  "RadioGroup": ['surface', 'brandSolid', 'neutralText', 'disabledBg', 'disabledText', 'border', 'fgMuted'],
  "Rating": ['neutralFill', 'neutralText', 'fgMuted', 'warningColor'],
  "ScrollArea": ['surface', 'neutralFill', 'neutralText', 'borderDefault'],
  "SegmentedControl": ['surface', 'neutralFill', 'neutralText', 'fgMuted'],
  "Select": ['neutralText', 'errorColor', 'disabledBg', 'disabledText', 'border', 'fgMuted', 'placeholderText'],
  "Sidebar": ['surface', 'brandSolid', 'brandText', 'neutralText', 'borderDefault'],
  "Slider": ['brandSolid', 'neutralFill', 'neutralText', 'fgMuted'],
  "SocialLoginButton": ['surface', 'neutralText', 'border'],
  "Spinner": ['brandSolid', 'neutralFill'],
  "StatusBadge": ['surface', 'neutralText', 'borderDefault'],
  "Stepper": ['brandSolid', 'brandText', 'onBrand', 'neutralFill', 'neutralText', 'fgMuted'],
  "SwitchGroup": ['surface', 'brandSolid', 'onBrand', 'neutralFill', 'neutralText', 'fgMuted'],
  "TabMenu": ['brandSolid', 'brandText', 'neutralText', 'fgMuted'],
  "Tabs": ['brandSolid', 'brandText', 'neutralText', 'borderDefault', 'fgMuted'],
  "Textarea": ['neutralText', 'errorColor', 'disabledBg', 'disabledText', 'border', 'fgMuted', 'placeholderText'],
  "TextLink": ['brandText', 'disabledText'],
  "Toast": ['surface', 'brandSolid', 'neutralText', 'errorColor', 'successColor', 'warningColor', 'infoColor'],
  "Toggle": ['surface', 'brandSolid', 'onBrand', 'neutralFill', 'neutralText', 'disabledBg', 'disabledText'],
  "Tooltip": ['surface', 'neutralText'],
}
