// GitHub OAuth App flow — replaces the manual Personal Access Token as the
// PRIMARY connect path (backlog item: "OAuth App flow (popup + serverless
// token exchange) to replace the manual PAT"). The PAT field in
// `GitHubConnectView` stays as a fallback — this doesn't remove it, both
// write through the SAME `setStoredToken` (`lib/github.ts`), so from every
// consumer's point of view a token is a token regardless of which door it
// came through.
//
// Why a popup, not a redirect of the whole app: this view is reached from
// deep inside the editor (Export wizard's "Connect GitHub" card, the Systems
// popover, SaveSidePanel) — a full-page redirect to github.com and back would
// blow away all of that in-memory navigation state for a connect step that
// only needs one value (the token). A popup keeps the opener alive.
//
// Why the client never touches a client_secret: it can't. GitHub's token
// exchange (`POST https://github.com/login/oauth/access_token`) requires the
// secret, and a secret shipped in a Vite bundle is not a secret. `api/
// github-oauth.ts` is the one place that holds it, server-side only.
//
// Why this endpoint issues the `authorize` REDIRECT too, instead of the
// client building that URL itself: the client_id isn't secret, but keeping it
// server-side means ZERO GitHub configuration has to be duplicated into a
// Vite env var — one env var pair (`GITHUB_OAUTH_CLIENT_ID` /
// `GITHUB_OAUTH_CLIENT_SECRET`), one place, both server-only. The endpoint is
// otherwise fully stateless: `state` is generated by THIS module, never by
// the server, and the server only ever relays it — nothing here needs a
// session store.

import { setStoredToken } from './github'
import { isLiveEnvironment } from './figmaSync'

const OAUTH_ENDPOINT = '/api/github-oauth'
const MESSAGE_SOURCE = 'escala-github-oauth'
const POPUP_FEATURES = 'width=560,height=680,menubar=no,toolbar=no,location=no,status=no'
// The popup can sit on GitHub's own login/consent screens for a while — this
// only bounds "nothing ever came back" (a closed popup, or a genuinely dead
// connection), not the user's own pace.
const TIMEOUT_MS = 5 * 60 * 1000

export type OAuthResult = { ok: true } | { ok: false; error: string }

interface OAuthMessage {
  source: string
  token?: string
  state?: string
  error?: string
}

function isOAuthMessage(data: unknown): data is OAuthMessage {
  return !!data && typeof data === 'object' && (data as { source?: unknown }).source === MESSAGE_SOURCE
}

/** Pure — the one place `state`/`token`/`error` get turned into a result, so
 *  `startGithubOAuth`'s DOM plumbing and this decision can be tested
 *  separately. Exported for `__tests__/githubOAuth.test.ts` only. */
export function interpretOAuthMessage(data: OAuthMessage, expectedState: string): OAuthResult {
  // Compared BEFORE reading `error`/`token` — a message whose state doesn't
  // match this popup's own request could be a stale message from a PREVIOUS
  // attempt (the listener is torn down on finish, but a message already in
  // flight when that happens is still a risk worth closing off explicitly).
  if (data.state !== expectedState) return { ok: false, error: 'state_mismatch' }
  if (data.error) return { ok: false, error: data.error }
  if (data.token) {
    setStoredToken(data.token)
    return { ok: true }
  }
  return { ok: false, error: 'no_token' }
}

/** OAuth is only OFFERED once the server side is configured — there is no
 *  client env var to read (see the file header), so the only way to know is
 *  to ask `api/github-oauth`. Short-circuits on `isLiveEnvironment()` first
 *  for the same reason every other publish-adjacent feature does (`canSync`
 *  in `HomeActions`, `useAutoFigmaSync`): `vite dev` has no `/api/*` route at
 *  all, and Vite's own SPA fallback serves `index.html` (200 OK) for an
 *  unmatched path, which would make the fetch alone report "configured" on
 *  localhost. */
export async function isGithubOAuthConfigured(): Promise<boolean> {
  if (!isLiveEnvironment()) return false
  try {
    const res = await fetch(`${OAUTH_ENDPOINT}?check=1`, { method: 'GET' })
    return res.ok
  } catch {
    return false
  }
}

/** Opens the GitHub OAuth popup and resolves once it completes — approved,
 *  denied, closed early, or timed out. Never rejects: every outcome is a
 *  value the caller renders, not an exception to catch. */
export function startGithubOAuth(): Promise<OAuthResult> {
  return new Promise((resolve) => {
    const state = crypto.randomUUID()
    const popup = window.open(`${OAUTH_ENDPOINT}?state=${encodeURIComponent(state)}`, MESSAGE_SOURCE, POPUP_FEATURES)
    if (!popup) {
      resolve({ ok: false, error: 'popup_blocked' })
      return
    }

    let settled = false
    function finish(result: OAuthResult) {
      if (settled) return
      settled = true
      window.removeEventListener('message', onMessage)
      window.clearInterval(poll)
      window.clearTimeout(timeout)
      resolve(result)
    }

    function onMessage(e: MessageEvent) {
      // The popup only ever runs `api/github-oauth`'s own response — same
      // origin as this app, since GitHub's registered redirect_uri IS this
      // app's domain. A stricter check would hardcode that domain; comparing
      // against `window.location.origin` instead means this also works
      // unmodified from a preview deployment that has its own OAuth App.
      if (e.origin !== window.location.origin) return
      if (!isOAuthMessage(e.data)) return
      finish(interpretOAuthMessage(e.data, state))
    }
    window.addEventListener('message', onMessage)

    // The popup navigates cross-origin (this app → github.com → this app) —
    // COOP means `popup.closed` is the ONLY thing observable about it from
    // here in between. Polling is what notices "the user closed it" when no
    // message is ever going to arrive.
    const poll = window.setInterval(() => {
      if (popup.closed) finish({ ok: false, error: 'closed' })
    }, 500)
    const timeout = window.setTimeout(() => {
      popup.close()
      finish({ ok: false, error: 'timeout' })
    }, TIMEOUT_MS)
  })
}
