// Which semantic roles a catalogue component actually paints with — the data
// behind Inspector mode's badge.
//
// DERIVED, never listed. `COMPONENT_COLOR_FIELDS` is generated by walking each
// specimen's own call graph (`npm run gen:component-color-fields`), and
// `CATEGORICAL_FIELD_ROLE` is the same table `resolvePreviewTokens` paints
// those fields from. Composing the two means the inspector can only ever name
// a role the component genuinely reads: a hand-written list here would be a
// second claim about token usage, free to drift from the render the moment a
// specimen changed which field it reaches for — which is the exact failure the
// generator exists to prevent.
//
// The cost of deriving it is a known blind spot, stated rather than hidden:
// see `INSPECTOR_BLIND_SPOT` below.

import { COMPONENT_COLOR_FIELDS } from './componentColorFields.generated'
import { CATEGORICAL_FIELD_ROLE } from './previewTokens'
import type { PreviewTokens } from '../components/preview/ButtonPreview'

/** Where a role was OBSERVED on the element — a fill, the ink of a glyph or
 *  a run of text, or a stroke. The badge shows it so a row reads as a place on
 *  the component rather than a name in a list. */
export type PaintSlot = 'fill' | 'ink' | 'stroke'

/**
 * A role the inspector reports for a component, with its value in the theme
 * currently on screen. `css` is whatever `archTokens` resolved — an 8-digit
 * hex for the 16 alpha-backed roles, so the badge must be able to render a
 * translucent swatch (see `TokenInspector`'s checkerboard).
 */
export interface InspectedRole {
  /** Fully qualified Categorical id — `action.primary.default`. */
  id: string
  css: string
  /** Absent when the row comes from the component's declared UNION rather
   *  than from a colour measured on the rendered element. */
  where?: PaintSlot
}

/** One element's roles, plus whether they were measured off the render. */
export interface Inspection {
  roles: InspectedRole[]
  /**
   * `false` when nothing on the element resolved to a role and `roles` is the
   * component's whole union instead — the honest wider answer, and the state
   * `INSPECTOR_BLIND_SPOT` is written for.
   */
  measured: boolean
}

/**
 * What the derivation CANNOT see, so nobody mistakes an empty badge for a
 * component that uses no colour.
 *
 * The covered path is a `PreviewTokens` field read inside `specimens.tsx`
 * (`t.brandSolid`) — the generator captures it and this module maps it back to
 * a role. Two paths escape it, and both are live today:
 *
 *  1. **Straight off the resolved map** — `t.archTokens['status.critical.border']`,
 *     which a dozen helpers in `specimens.tsx` do (`statusInk`, `statusOn`,
 *     `statusBorder`, `slotOf`). The generator records the FIELD closure, not
 *     those literal ids.
 *  2. **Through a helper in ANOTHER MODULE** — the walk is scoped to
 *     `specimens.tsx`'s own AST, so a field read inside e.g.
 *     `previewTokens.ts`'s `overlaySurfaceOf` is invisible to it. This is why
 *     Modal · Combobox · Command · ContextMenu report no `surface.page` /
 *     `surface.layer-1` despite painting with them: the specimens moved that
 *     read into `overlaySurfaceStyle`, and the generated field list narrowed
 *     to match the walk rather than the render.
 *
 * UPDATE: both escapes are closed for a MEASURED inspection — `inspectElement`
 * reads the colours off the rendered element, where an `archTokens` read and a
 * read through another module are indistinguishable from any other paint. This
 * constant is now only shown when the measurement found nothing and the badge
 * fell back to the union below (`Inspection.measured === false`), which is the
 * one state where the derivation is still the field closure.
 *
 * Left as a gap on purpose rather than patched with a hardcoded supplement:
 * a hand-kept list of "roles the generator misses" is precisely the drifting
 * second source this module's header rejects. The real fix is in the
 * generator — following imported helpers for (2) and collecting
 * `archTokens[...]` string literals for (1), along the same closure it already
 * walks — at which point this constant and the badge's own footnote both go
 * away. Both cases UNDER-report; the badge never names a role a component
 * doesn't read, so what's here is always true, just not always complete.
 */
export const INSPECTOR_BLIND_SPOT =
  'Roles read straight from archTokens (status borders, ghost washes) are not listed.'

/**
 * Field → role, inverted once. Several fields can share a role; the id is what
 * the badge shows, so duplicates collapse.
 *
 * THIS IS THE COMPONENT'S UNION, NOT THE RENDERED VARIANT.
 * `COMPONENT_COLOR_FIELDS` is the union over a specimen's whole axis matrix,
 * so a Solid Brand button reports the four `status.*` solids its
 * Danger/Success variants use too. That is the right answer to "which roles
 * does this component consume" and the wrong one to "which roles paint THIS
 * button" — `inspectElement` below answers the second by measuring the render,
 * and uses this list to disambiguate. Two jobs, two functions; don't collapse
 * them.
 */
export function rolesForComponent(componentKey: string): string[] {
  const fields = COMPONENT_COLOR_FIELDS[componentKey]
  if (!fields) return []
  const ids: string[] = []
  for (const field of fields) {
    const id = CATEGORICAL_FIELD_ROLE[field]
    if (id && !ids.includes(id)) ids.push(id)
  }
  return ids
}

/**
 * The roles for a component, resolved against the theme on screen.
 *
 * A role with no entry in `archTokens` is DROPPED, not shown as a blank: the
 * map is populated only under the Categorical architecture, and a badge
 * listing ids with no colour beside them would imply the tokens are broken
 * rather than that the projection isn't active.
 */
export function inspectComponent(t: PreviewTokens, componentKey: string): InspectedRole[] {
  const arch = t.archTokens
  if (!arch) return []
  return rolesForComponent(componentKey)
    .map((id) => ({ id, css: arch[id] }))
    .filter((r): r is InspectedRole => !!r.css)
}

// ── Measured inspection: which roles paint THIS element ──────────────────────
//
// Pointing at one Solid button and being handed ten roles — six of which
// belong to variants that aren't on screen — is the component's answer to a
// question about a pixel. The fix is to ask the render: read the computed
// colours off the element and match them back to the theme's own resolved
// values, so a Solid Brand button reports exactly its fill and its label ink.
//
// DERIVED, like everything else here, and derived one step CLOSER to the truth
// than the field closure: a colour on screen cannot be a colour the component
// doesn't paint. It also closes half of `INSPECTOR_BLIND_SPOT` for free — a
// role read straight off `archTokens` (`status.*.border`, `surface.input`, the
// ghost washes) is invisible to the generator's AST walk but perfectly visible
// as a border colour in `getComputedStyle`.
//
// The declared union stays load-bearing for DISAMBIGUATION. Roles legitimately
// share values (`content.on-action == content.inverse`, `surface.inverse ==
// surface.overlay` in light), so one observed hex can name two roles; the one
// the component actually reads wins. Without that step a Solid button would
// report `content.inverse` beside `content.on-action` and be right twice about
// the same pixel, which is exactly the noise this is removing.

/** How many descendants to read per element. A collage module is ~40 nodes;
 *  the cap only exists so a pathological subtree can't stall a pointermove. */
const MAX_NODES = 400

const rgbaKey = (r: number, g: number, b: number, a: number) =>
  `${r},${g},${b},${a.toFixed(2)}`

/**
 * A CSS colour reduced to `r,g,b,a` so a computed style (`rgb()` / `rgba()`)
 * can be compared with a token's hex.
 *
 * Alpha is compared at two decimals, and that is exact rather than tolerant:
 * both sides descend from the same 8-bit channel — the token's `aa` and the
 * value the browser resolved from it — so they round identically.
 *
 * Fully transparent returns `null`: nothing is painted, and `transparent` is
 * what every specimen writes for "this style has no fill/stroke", so matching
 * it would report a role for the absence of one.
 */
function normalizeColor(css: string | null | undefined): string | null {
  if (!css) return null
  const value = css.trim().toLowerCase()
  if (!value || value === 'transparent' || value === 'currentcolor' || value === 'none') return null

  if (value[0] === '#') {
    const hex = value.slice(1)
    if (hex.length !== 3 && hex.length !== 4 && hex.length !== 6 && hex.length !== 8) return null
    const short = hex.length <= 4
    const channel = (i: number) =>
      parseInt(short ? hex[i] + hex[i] : hex.slice(i * 2, i * 2 + 2), 16)
    const r = channel(0), g = channel(1), b = channel(2)
    if (!Number.isFinite(r) || !Number.isFinite(g) || !Number.isFinite(b)) return null
    const alpha = short ? hex.length === 4 : hex.length === 8
    const a = alpha ? channel(3) / 255 : 1
    return a === 0 ? null : rgbaKey(r, g, b, a)
  }

  if (!value.startsWith('rgb')) return null
  const parts = value.match(/-?[\d.]+%?/g)
  if (!parts || parts.length < 3) return null
  const channel = (raw: string) =>
    Math.round(raw.endsWith('%') ? parseFloat(raw) * 2.55 : parseFloat(raw))
  const r = channel(parts[0]), g = channel(parts[1]), b = channel(parts[2])
  const raw = parts[3]
  const a = raw == null ? 1 : (raw.endsWith('%') ? parseFloat(raw) / 100 : parseFloat(raw))
  if (![r, g, b, a].every(Number.isFinite)) return null
  return a === 0 ? null : rgbaKey(r, g, b, a)
}

/** value → role ids, built once per resolved token map. Several roles can
 *  share a value, so this is one-to-many by construction. */
const INDEX_CACHE = new WeakMap<Record<string, string>, Map<string, string[]>>()

function roleIndex(arch: Record<string, string>): Map<string, string[]> {
  const cached = INDEX_CACHE.get(arch)
  if (cached) return cached
  const index = new Map<string, string[]>()
  for (const [id, css] of Object.entries(arch)) {
    const key = normalizeColor(css)
    if (!key) continue
    const bucket = index.get(key)
    if (bucket) bucket.push(id)
    else index.set(key, [id])
  }
  INDEX_CACHE.set(arch, index)
  return index
}

/**
 * Ink is only painted where there are glyphs. `color` inherits, so every
 * wrapper in the subtree reports the page's text colour whether it renders a
 * character or not — which is how a Solid button ends up claiming
 * `content.primary` from the `Live` wrapper around it. A node with no direct
 * text node paints no ink.
 */
function paintsText(node: Element): boolean {
  for (const child of Array.from(node.childNodes)) {
    if (child.nodeType === 3 && (child.textContent ?? '').trim()) return true
  }
  return false
}

interface Observation { key: string; where: PaintSlot }

/** Every colour the element and its descendants actually paint, in paint
 *  order — fill, then ink, then strokes, walking down the tree. */
function observePaints(root: Element): Observation[] {
  const out: Observation[] = []
  const seen = new Set<string>()
  const push = (css: string | null | undefined, where: PaintSlot) => {
    const key = normalizeColor(css)
    if (!key) return
    const tag = `${key}|${where}`
    if (seen.has(tag)) return
    seen.add(tag)
    out.push({ key, where })
  }

  const nodes = [root, ...Array.from(root.querySelectorAll('*')).slice(0, MAX_NODES)]
  for (const node of nodes) {
    const cs = getComputedStyle(node)
    // A `display: contents` marker generates no box, so it paints nothing —
    // reading it would attribute its inherited ink to the component.
    if (cs.display === 'contents') continue
    const masked = (cs.maskImage && cs.maskImage !== 'none') || (cs.webkitMaskImage && cs.webkitMaskImage !== 'none')
    // A masked span IS a glyph (see `PreviewIcon`): its background is the
    // icon's ink, not a surface fill.
    push(cs.backgroundColor, masked ? 'ink' : 'fill')
    if (paintsText(node)) push(cs.color, 'ink')
    for (const side of ['Top', 'Right', 'Bottom', 'Left'] as const) {
      const width = parseFloat(cs.getPropertyValue(`border-${side.toLowerCase()}-width`))
      if (!(width > 0)) continue
      if (cs.getPropertyValue(`border-${side.toLowerCase()}-style`) === 'none') continue
      push(cs.getPropertyValue(`border-${side.toLowerCase()}-color`), 'stroke')
    }
    if (parseFloat(cs.outlineWidth) > 0 && cs.outlineStyle !== 'none') push(cs.outlineColor, 'stroke')
  }
  return out
}

/**
 * The roles ONE rendered element paints, ordered the way it paints them.
 *
 * Falls back to the component's union (`measured: false`) when nothing
 * matched — a flat-architecture system has no `archTokens` at all, and a
 * specimen can legitimately paint only inherited or `transparent` colours.
 * An empty badge would read as "this component uses no colour", which is never
 * what happened.
 */
export function inspectElement(
  t: PreviewTokens, componentKey: string, el: Element,
): Inspection {
  const arch = t.archTokens
  if (!arch) return { roles: [], measured: false }
  const declared = rolesForComponent(componentKey)
  const index = roleIndex(arch)
  const roles: InspectedRole[] = []
  for (const paint of observePaints(el)) {
    const candidates = index.get(paint.key)
    if (!candidates) continue
    const owned = candidates.filter((id) => declared.includes(id))
    for (const id of owned.length ? owned : candidates) {
      if (roles.some((role) => role.id === id)) continue
      roles.push({ id, css: arch[id], where: paint.where })
    }
  }
  if (roles.length) return { roles, measured: true }
  return { roles: inspectComponent(t, componentKey), measured: false }
}

/** A group's members and their combined roles. */
export interface GroupInspection {
  roles: InspectedRole[]
  /** Catalogue keys of the inspectable components inside, in DOM order. */
  members: string[]
}

/**
 * Every role painted by the components INSIDE a container — the answer to
 * "what does this whole cluster consume", which is the question you're asking
 * when you point at the box rather than at one control in it.
 *
 * Membership is read from the DOM (`[data-inspect]` descendants), never
 * declared on the container: a module that gains a component gains its roles
 * here with nothing to update, and a label listing components a module no
 * longer holds is impossible to write.
 */
export function inspectGroup(t: PreviewTokens, el: Element): GroupInspection {
  const members: string[] = []
  const roles: InspectedRole[] = []
  for (const child of Array.from(el.querySelectorAll('[data-inspect]'))) {
    const key = child.getAttribute('data-inspect') || ''
    if (!key) continue
    members.push(key)
    for (const role of inspectElement(t, key, child).roles) {
      if (roles.some((existing) => existing.id === role.id)) continue
      roles.push(role)
    }
  }
  return { roles, members }
}
