import { figmaSemanticName, webCodeSyntax } from './names'
import type { TokenJSON } from './types'
import type { AgentBundleFile } from './types'

function projectName(json: TokenJSON): string {
  return json.project?.trim() || 'Design system'
}

export function buildContextFiles(json: TokenJSON): AgentBundleFile[] {
  const project = projectName(json)
  return [
    { path: 'AGENTS.md', text: buildAgentsMd(json, project) },
    { path: 'llms.txt', text: buildLlmsTxt(json, project) },
  ]
}

function buildAgentsMd(json: TokenJSON, project: string): string {
  const icons = json.icons?.aiSource
  return [
    `---`,
    `source: escala-tokens`,
    `format: agent-context/v1`,
    `scope: global`,
    `title: ${project}`,
    `---`,
    ``,
    `# ${project}`,
    ``,
    `This folder is the design system. Prefer these token names over exploring the repo.`,
    `Do not invent parallel names, hex, or px when a token exists. Bind paints to semantic roles only.`,
    ``,
    `## Read this, then stop`,
    ``,
    `| Need | File |`,
    `|---|---|`,
    `| Figma variables, modes, scopes | \`SKILL.md\` |`,
    `| Resolved hex | \`references/tokens.md\` |`,
    `| Type, spacing, radius, size, grid | \`references/foundations.md\` |`,
    `| Role → Figma / CSS / scopes | \`references/semantic-contract.md\` |`,
    `| Implement UI in code | \`skills/code/SKILL.md\` |`,
    `| Contrast / a11y | \`skills/a11y-audit/SKILL.md\` |`,
    `| Replace hardcoded hex/px | \`skills/migrate/SKILL.md\` |`,
    `| Component scaffolds | \`templates/component/\` |`,
    `| Lint leftover hex/px | \`checkers/token-lint.mjs\` |`,
    ``,
    `## Hard rules`,
    ``,
    `1. Semantics over primitives. \`${figmaSemanticName('action.primary.default')}\` not a raw ramp step.`,
    `2. Figma names use \`/\`. CSS uses hyphens inside \`var()\`: \`${webCodeSyntax('action.primary.default')}\`.`,
    `3. Pair fills with their ink: Action/primary/* → Content/on-action. Status surface → Status content. Inputs: Surface/input + Border/strong. Focus: Border/focus, never Border/accent.`,
    `4. Icons: ${icons?.repo ? `only ${icons.repo} (\`${icons.npm}\`)` : 'only the set named under Icons in SKILL.md'}. Do not mix families.`,
    `5. If a name is not in the Token catalog, do not invent it.`,
    ``,
    `Architecture: \`${json.colors.semanticArchitecture ?? json.colors.architecture?.kind ?? 'categorical'}\`.`,
    json.atoms?.length ? `Selected components (\`atoms\`): ${json.atoms.join(', ')}.` : '',
    ``,
  ].filter((line, i, arr) => line !== '' || arr[i - 1] !== '').join('\n')
}

function buildLlmsTxt(json: TokenJSON, project: string): string {
  const icons = json.icons?.aiSource
  return [
    `# ${project}`,
    ``,
    `> Design tokens generated by Escala. Semantic roles are the public API. Primitives are hidden.`,
    ``,
    `## Context`,
    ``,
    `- [AGENTS.md](AGENTS.md): Router — do not invent names`,
    `- [Figma skill](SKILL.md): Collections, scopes, WEB code syntax`,
    `- [Tokens](references/tokens.md): Resolved color values`,
    `- [Foundations](references/foundations.md): Type, spacing, radius, size, grid, shadow`,
    `- [Semantic contract](references/semantic-contract.md): Role ↔ Figma ↔ CSS`,
    ``,
    `## Knowledge`,
    ``,
    `- [Implement UI](skills/code/SKILL.md)`,
    `- [Audit contrast](skills/a11y-audit/SKILL.md)`,
    `- [Migrate hex/px](skills/migrate/SKILL.md)`,
    ``,
    `## Generation`,
    ``,
    `- [Component templates](templates/component/)`,
    ``,
    `## Validation`,
    ``,
    `- [token-lint](checkers/token-lint.mjs): flags hex/px that already have a token`,
    ``,
    icons?.repo ? `## Icons\n\n- ${icons.label}: ${icons.repo} (\`${icons.npm}\`)\n` : '',
    `Do not point agents at a different product's MCP. Wire this system's own token endpoint when you have one.`,
    ``,
  ].join('\n')
}
