import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { useDesignStore } from '../../store/useDesignStore'
import { generateTokenJSON } from '../../lib/tokenGenerator'

type Tab = 'tokens' | 'css' | 'markdown'

// Human-readable labels for the style direction key
const STYLE_LABEL: Record<string, string> = {
  ios26: 'iOS 26',
  organic: 'Organic',
  material: 'Material',
}

// ─── Generators ─────────────────────────────────────────────────────────────

function buildCSS(store: ReturnType<typeof useDesignStore.getState>): string {
  const { primaryScale, semanticTokens, typography, spacing, radius } = store
  const lines: string[] = [':root {']

  lines.push('  /* Primitive scale */')
  Object.entries(primaryScale)
    .sort(([a], [b]) => Number(a) - Number(b))
    .forEach(([k, v]) => lines.push(`  --color-${k}: ${v};`))

  lines.push('\n  /* Semantic tokens */')
  Object.entries(semanticTokens).forEach(([k, v]) => {
    if (v) lines.push(`  --color-${k.replace(/([A-Z])/g, '-$1').toLowerCase()}: ${v};`)
  })

  lines.push('\n  /* Typography */')
  lines.push(`  --font-family-heading: '${typography.headingFontFamily ?? typography.fontFamily}', sans-serif;`)
  lines.push(`  --font-family-body: '${typography.fontFamily}', sans-serif;`)
  Object.entries(typography.sizes).forEach(([k, v]) => lines.push(`  --font-size-${k}: ${v};`))
  Object.entries(typography.weights).forEach(([k, v]) => lines.push(`  --font-weight-${k}: ${v};`))

  lines.push('\n  /* Spacing */')
  Object.entries(spacing).forEach(([k, v]) => lines.push(`  --spacing-${k}: ${v};`))

  lines.push('\n  /* Radius */')
  Object.entries(radius).forEach(([k, v]) => lines.push(`  --radius-${k}: ${v};`))

  lines.push('}')
  return lines.join('\n')
}

function buildMarkdown(store: ReturnType<typeof useDesignStore.getState>): string {
  const { projectName, primaryColor, primaryScale, semanticTokens, typography, spacing, radius, styleDirection, selectedAtoms } = store
  const slug = projectName.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')
  const headingFont = typography.headingFontFamily ?? typography.fontFamily

  return `# ${projectName} — Design System

> Generated by [Scalable Designs](https://scalable-designs.vercel.app)

## Overview

- **Style direction:** ${styleDirection ? STYLE_LABEL[styleDirection] ?? styleDirection : 'not set'}
- **Primary color:** \`${primaryColor}\`
- **Heading font:** ${headingFont}
- **Body font:** ${typography.fontFamily}
- **Atoms included:** ${selectedAtoms.length > 0 ? selectedAtoms.join(', ') : 'none selected'}

---

## Color Tokens

### Primitive Scale

| Token | Value |
|-------|-------|
${Object.entries(primaryScale).sort(([a],[b])=>Number(a)-Number(b)).map(([k,v])=>`| \`--color-${k}\` | \`${v}\` |`).join('\n')}

### Semantic Tokens

| Token | Value |
|-------|-------|
${Object.entries(semanticTokens).filter(([,v])=>v).map(([k,v])=>`| \`--color-${k.replace(/([A-Z])/g,'-$1').toLowerCase()}\` | \`${v}\` |`).join('\n')}

---

## Typography

| Token | Value |
|-------|-------|
| \`--font-family-heading\` | \`'${headingFont}', sans-serif\` |
| \`--font-family-body\` | \`'${typography.fontFamily}', sans-serif\` |
${Object.entries(typography.sizes).map(([k,v])=>`| \`--font-size-${k}\` | \`${v}\` |`).join('\n')}
${Object.entries(typography.weights).map(([k,v])=>`| \`--font-weight-${k}\` | \`${v}\` |`).join('\n')}

---

## Spacing

| Token | Value |
|-------|-------|
${Object.entries(spacing).map(([k,v])=>`| \`--spacing-${k}\` | \`${v}\` |`).join('\n')}

---

## Border Radius

| Token | Value |
|-------|-------|
${Object.entries(radius).map(([k,v])=>`| \`--radius-${k}\` | \`${v}\` |`).join('\n')}

---

## Atoms

${selectedAtoms.length > 0
  ? selectedAtoms.map(a => `- \`${a}\``).join('\n')
  : '_No atoms selected._'}

---

*Token namespace: \`${slug}\`*
`
}

// ─── Download helpers ────────────────────────────────────────────────────────

function download(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// ─── Summary pill ────────────────────────────────────────────────────────────

function Pill({ label, value, color }: { label: string; value: string; color?: string }) {
  return (
    <div className="flex flex-col gap-0.5 px-4 py-3 rounded-xl bg-neutral-900 border border-neutral-800 min-w-0">
      <span className="text-[10px] text-neutral-600 uppercase tracking-wider">{label}</span>
      <div className="flex items-center gap-1.5">
        {color && (
          <div className="w-3 h-3 rounded-full flex-shrink-0" style={{ backgroundColor: color }} />
        )}
        <span className="text-sm font-medium text-white truncate">{value}</span>
      </div>
    </div>
  )
}

// ─── Main ────────────────────────────────────────────────────────────────────

export default function Step8_Export() {
  const store = useDesignStore()
  const { projectName, primaryColor, styleDirection, selectedAtoms } = store
  const [activeTab, setActiveTab] = useState<Tab>('tokens')
  const [copiedTab, setCopiedTab] = useState<Tab | null>(null)
  const [justDownloaded, setJustDownloaded] = useState<string | null>(null)

  const [isDeployed, setIsDeployed] = useState(false)
  useEffect(() => {
    const origin = window.location.origin
    setIsDeployed(!origin.includes('localhost') && !origin.includes('127.0.0.1'))
  }, [])

  const slug = projectName.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '') || 'scalable-designs'

  const tokenJSON = JSON.stringify(generateTokenJSON(), null, 2)
  const cssVars   = buildCSS(useDesignStore.getState())
  const markdown  = buildMarkdown(useDesignStore.getState())

  const TABS: { id: Tab; label: string }[] = [
    { id: 'tokens',   label: 'tokens.json' },
    { id: 'css',      label: 'variables.css' },
    { id: 'markdown', label: 'README.md' },
  ]

  const content: Record<Tab, string> = { tokens: tokenJSON, css: cssVars, markdown }

  async function copyTab(tab: Tab) {
    await navigator.clipboard.writeText(content[tab])
    setCopiedTab(tab)
    setTimeout(() => setCopiedTab(null), 2000)
  }

  function downloadAll() {
    download(tokenJSON, `${slug}-tokens.json`, 'application/json')
    setTimeout(() => download(cssVars, `${slug}-variables.css`, 'text/css'), 200)
    setTimeout(() => download(markdown, `${slug}-README.md`, 'text/markdown'), 400)
    setJustDownloaded('all')
    setTimeout(() => setJustDownloaded(null), 2500)
  }

  function downloadOne(tab: Tab) {
    const ext: Record<Tab, string> = { tokens: 'tokens.json', css: 'variables.css', markdown: 'README.md' }
    const mime: Record<Tab, string> = { tokens: 'application/json', css: 'text/css', markdown: 'text/markdown' }
    download(content[tab], `${slug}-${ext[tab]}`, mime[tab])
    setJustDownloaded(tab)
    setTimeout(() => setJustDownloaded(null), 2500)
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3, ease: 'easeOut' }}
      className="flex flex-col gap-8"
    >
      {/* ── Summary ── */}
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
        <Pill label="Project"   value={projectName || '—'} />
        <Pill label="Primary"   value={primaryColor}       color={primaryColor} />
        <Pill label="Style"     value={styleDirection ? STYLE_LABEL[styleDirection] ?? styleDirection : '—'} />
        <Pill label="Atoms"     value={`${selectedAtoms.length} selected`} />
      </div>

      {/* ── File tabs ── */}
      <div className="flex flex-col gap-0">
        <div className="flex items-center justify-between border-b border-neutral-800">
          <div className="flex">
            {TABS.map((t) => (
              <button
                key={t.id}
                onClick={() => setActiveTab(t.id)}
                className={`px-4 py-2.5 text-xs font-mono transition-all border-b-2 ${
                  activeTab === t.id
                    ? 'text-white border-violet-500'
                    : 'text-neutral-500 border-transparent hover:text-neutral-300'
                }`}
              >
                {t.label}
              </button>
            ))}
          </div>
          <div className="flex gap-2 pr-1">
            <button
              onClick={() => copyTab(activeTab)}
              className="flex items-center gap-1.5 px-2.5 py-1 text-xs rounded bg-neutral-800 text-neutral-300 hover:bg-neutral-700 transition border border-neutral-700"
            >
              {copiedTab === activeTab ? (
                <><span className="text-emerald-400">✓</span> Copied</>
              ) : (
                <>
                  <svg width="11" height="11" viewBox="0 0 11 11" fill="none"><rect x="1" y="3" width="7" height="7" rx="1" stroke="currentColor" strokeWidth="1.2"/><path d="M3 3V2a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1H8" stroke="currentColor" strokeWidth="1.2"/></svg>
                  Copy
                </>
              )}
            </button>
            <button
              onClick={() => downloadOne(activeTab)}
              className="flex items-center gap-1.5 px-2.5 py-1 text-xs rounded bg-neutral-800 text-neutral-300 hover:bg-neutral-700 transition border border-neutral-700"
            >
              {justDownloaded === activeTab ? (
                <><span className="text-emerald-400">✓</span> Saved</>
              ) : (
                <>
                  <svg width="11" height="11" viewBox="0 0 11 11" fill="none"><path d="M5.5 1v6M3 5l2.5 2.5L8 5" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/><path d="M1 8.5v1a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-1" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/></svg>
                  Download
                </>
              )}
            </button>
          </div>
        </div>

        <AnimatePresence mode="wait">
          <motion.div
            key={activeTab}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.15 }}
            className="bg-neutral-950 border border-t-0 border-neutral-800 rounded-b-xl overflow-auto max-h-72"
          >
            <pre className="p-4 text-[11px] font-mono leading-relaxed text-neutral-300 whitespace-pre">
              {content[activeTab]}
            </pre>
          </motion.div>
        </AnimatePresence>
      </div>

      {/* ── Download all CTA ── */}
      <div className="flex flex-col gap-3 items-center rounded-xl border border-neutral-800 bg-neutral-900/50 p-6">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ backgroundColor: primaryColor + '22', border: `1px solid ${primaryColor}44` }}>
            <svg width="18" height="18" viewBox="0 0 18 18" fill="none">
              <path d="M9 2v10M5.5 8l3.5 4 3.5-4" stroke={primaryColor} strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/>
              <path d="M2 13.5v1.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-1.5" stroke={primaryColor} strokeWidth="1.6" strokeLinecap="round"/>
            </svg>
          </div>
          <div>
            <p className="text-sm font-semibold text-white">Export all files</p>
            <p className="text-xs text-neutral-500">tokens.json · variables.css · README.md</p>
          </div>
        </div>

        <motion.button
          onClick={downloadAll}
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
          className="w-full py-3 rounded-xl text-sm font-semibold transition-all"
          style={{
            backgroundColor: justDownloaded === 'all' ? '#10b981' : primaryColor,
            color: '#fff',
            boxShadow: `0 4px 20px ${primaryColor}44`,
          }}
        >
          {justDownloaded === 'all' ? '✓ Downloaded!' : `Download ${slug}-tokens`}
        </motion.button>
      </div>

      {/* ── What's next ── */}
      <div className="grid grid-cols-3 gap-3">
        {[
          {
            icon: '⌗',
            title: 'Use in code',
            desc: 'Import variables.css and reference tokens via CSS custom properties in any framework.',
          },
          {
            icon: '⬡',
            title: 'Figma sync',
            desc: isDeployed
              ? 'Publish tokens to /api/tokens so your Figma plugin can poll and sync them automatically.'
              : 'Deploy to a live URL first, then use the publish endpoint to sync with Figma plugins.',
          },
          {
            icon: '↻',
            title: 'Iterate',
            desc: 'Your configuration is saved automatically. Come back any time to refine your tokens.',
          },
        ].map((item) => (
          <div key={item.title} className="rounded-xl bg-neutral-900 border border-neutral-800 p-4 flex flex-col gap-2">
            <span className="text-xl">{item.icon}</span>
            <p className="text-sm font-medium text-white">{item.title}</p>
            <p className="text-xs text-neutral-500 leading-relaxed">{item.desc}</p>
          </div>
        ))}
      </div>

      {/* ── Publish endpoint — only shown when deployed ── */}
      {isDeployed && (
        <div className="rounded-xl border border-neutral-800 bg-neutral-900/50 p-5 flex flex-col gap-3">
          <div className="flex items-center gap-2">
            <div className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
            <p className="text-sm font-semibold text-white">Live publish endpoint</p>
          </div>
          <p className="text-xs text-neutral-500">
            POST to <code className="text-violet-400 text-[11px] px-1 py-0.5 rounded bg-neutral-800">/api/tokens</code> to push your current token set. Use this URL in your Figma plugin's live sync configuration.
          </p>
          <div className="flex items-center gap-2 bg-neutral-950 border border-neutral-800 rounded-lg px-3 py-2">
            <code className="text-xs text-violet-400 flex-1 truncate font-mono">
              {window.location.origin}/api/tokens
            </code>
            <button
              onClick={() => navigator.clipboard.writeText(`${window.location.origin}/api/tokens`)}
              className="text-[10px] text-neutral-500 hover:text-white transition flex-shrink-0"
            >
              Copy
            </button>
          </div>
        </div>
      )}
    </motion.div>
  )
}
