import type { VercelRequest, VercelResponse } from '@vercel/node'

// GitHub OAuth App token exchange — the one place `GITHUB_OAUTH_CLIENT_SECRET`
// is allowed to exist. See `src/lib/githubOAuth.ts` for the full flow this is
// one half of, and why it's designed to be entirely stateless (no session
// store: `state` is generated by the CLIENT and only ever relayed here).
//
// Three GET shapes hit this one handler, distinguished by query params —
// same "one file per API concern" shape `api/tokens.ts`/`api/mcp.ts` already
// use, not three separate serverless functions for one feature:
//
//   ?check=1           → 200 if the server side is configured, else 404.
//                         No secrets in the response either way.
//   ?state=<s>          → the popup's FIRST hop. 302 straight to GitHub's own
//                         authorize screen with our client_id.
//   ?code=<c>&state=<s> → GitHub's callback. Exchanges the code, then serves
//                         a tiny HTML page that posts the result back to
//                         `window.opener` and closes itself.
//
// Must exactly match this OAuth App's registered "Authorization callback
// URL" — GitHub rejects the exchange on any mismatch, including scheme/host.
const REDIRECT_URI = 'https://www.escalatokens.com/api/github-oauth'
const MESSAGE_SOURCE = 'escala-github-oauth'

function html(body: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><title>Connecting to GitHub…</title></head>` +
    `<body style="font:14px -apple-system,system-ui,sans-serif;color:#6b7280;display:flex;align-items:center;justify-content:center;height:100vh;margin:0">` +
    `<p>${body}</p></body></html>`
}

/** `window.opener.postMessage(...)` + `window.close()`, inlined as the page's
 *  only script. `payload` is JSON-serialised server-side and re-parsed as a
 *  JS object literal client-side — safe here (no user-controlled string
 *  reaches this unescaped except `code`/`state`, which only ever flow into
 *  `JSON.stringify`, never into the HTML around it). */
function closeWith(payload: Record<string, string>): string {
  const data = JSON.stringify({ source: MESSAGE_SOURCE, ...payload })
  return html(
    `Connecting to GitHub…</p><script>` +
    `window.opener && window.opener.postMessage(${data}, window.location.origin);` +
    `window.close();` +
    `</script><p style="margin-top:8px;font-size:12px">` +
    `You can close this window.`,
  )
}

function readParam(req: VercelRequest, key: string): string | null {
  const v = req.query[key]
  return typeof v === 'string' && v ? v : null
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  const clientId = process.env.GITHUB_OAUTH_CLIENT_ID
  const clientSecret = process.env.GITHUB_OAUTH_CLIENT_SECRET

  if (readParam(req, 'check')) {
    // Deliberately no body distinguishing "not configured" from any other
    // failure — this exists only to gate whether the UI OFFERS the OAuth
    // button, not to explain a misconfiguration to an end user.
    res.status(clientId && clientSecret ? 200 : 404).end()
    return
  }

  res.setHeader('Content-Type', 'text/html; charset=utf-8')
  res.setHeader('Cache-Control', 'no-store')

  if (!clientId || !clientSecret) {
    res.status(500).send(closeWith({ error: 'not_configured' }))
    return
  }

  const code = readParam(req, 'code')
  const state = readParam(req, 'state')
  const upstreamError = readParam(req, 'error')

  // No code yet — the popup's first hop. `state` is REQUIRED here (not just
  // relayed): without it this endpoint would be an open redirector to GitHub
  // with no way for the opener to later tell its own popup's response apart
  // from a stale or forged one.
  if (!code) {
    if (upstreamError) {
      res.status(200).send(closeWith({ error: upstreamError }))
      return
    }
    if (!state) {
      res.status(400).send(closeWith({ error: 'missing_state' }))
      return
    }
    const authorize = new URL('https://github.com/login/oauth/authorize')
    authorize.searchParams.set('client_id', clientId)
    authorize.searchParams.set('redirect_uri', REDIRECT_URI)
    authorize.searchParams.set('scope', 'repo')
    authorize.searchParams.set('state', state)
    res.writeHead(302, { Location: authorize.toString() }).end()
    return
  }

  // GitHub redirected back with a code — exchange it for an access token.
  try {
    const tokenRes = await fetch('https://github.com/login/oauth/access_token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
      body: JSON.stringify({
        client_id: clientId,
        client_secret: clientSecret,
        code,
        redirect_uri: REDIRECT_URI,
      }),
    })
    const body = (await tokenRes.json()) as {
      access_token?: string
      error?: string
      error_description?: string
    }
    if (!tokenRes.ok || !body.access_token) {
      res.status(200).send(closeWith({ error: body.error_description || body.error || 'exchange_failed', state: state ?? '' }))
      return
    }
    res.status(200).send(closeWith({ token: body.access_token, state: state ?? '' }))
  } catch {
    res.status(200).send(closeWith({ error: 'network_error', state: state ?? '' }))
  }
}
