/**
 * GENERATED FILE — do not edit by hand.
 * Regenerate with `npm run gen:carbon-reference`.
 *
 * IBM Carbon's palette, its four themes, and every core UI token expressed as
 * the palette stop IBM chose. Carbon's scales are hand-tuned IBM brand values —
 * there is no generator to port, the same as Tailwind.
 *
 * Sources: @carbon/colors@11.56.0, @carbon/themes@11.79.0
 */

export const CARBON_COLORS_VERSION = '11.56.0'
export const CARBON_THEMES_VERSION = '11.79.0'

/** Carbon scale stops, lightest to darkest. */
export const CARBON_STOPS = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100] as const

export const CARBON_FAMILY_NAMES = [
  'blue',
  'cyan',
  'gray',
  'coolGray',
  'warmGray',
  'green',
  'magenta',
  'orange',
  'purple',
  'red',
  'teal',
  'yellow',
] as const

export const CARBON_NEUTRAL_FAMILY_NAMES = ['gray', 'coolGray', 'warmGray'] as const

/** Theme names, lightest page to darkest. */
export const CARBON_THEME_NAMES = ['white', 'g10', 'g90', 'g100'] as const

/** `family → hex per stop`, index-aligned with `CARBON_STOPS`. */
export const CARBON_PALETTE: Record<string, readonly string[]> = {
  blue: ['#edf5ff', '#d0e2ff', '#a6c8ff', '#78a9ff', '#4589ff', '#0f62fe', '#0043ce', '#002d9c', '#001d6c', '#001141'],
  cyan: ['#e5f6ff', '#bae6ff', '#82cfff', '#33b1ff', '#1192e8', '#0072c3', '#00539a', '#003a6d', '#012749', '#061727'],
  gray: ['#f4f4f4', '#e0e0e0', '#c6c6c6', '#a8a8a8', '#8d8d8d', '#6f6f6f', '#525252', '#393939', '#262626', '#161616'],
  coolGray: ['#f2f4f8', '#dde1e6', '#c1c7cd', '#a2a9b0', '#878d96', '#697077', '#4d5358', '#343a3f', '#21272a', '#121619'],
  warmGray: ['#f7f3f2', '#e5e0df', '#cac5c4', '#ada8a8', '#8f8b8b', '#726e6e', '#565151', '#3c3838', '#272525', '#171414'],
  green: ['#defbe6', '#a7f0ba', '#6fdc8c', '#42be65', '#24a148', '#198038', '#0e6027', '#044317', '#022d0d', '#071908'],
  magenta: ['#fff0f7', '#ffd6e8', '#ffafd2', '#ff7eb6', '#ee5396', '#d02670', '#9f1853', '#740937', '#510224', '#2a0a18'],
  orange: ['#fff2e8', '#ffd9be', '#ffb784', '#ff832b', '#eb6200', '#ba4e00', '#8a3800', '#5e2900', '#3e1a00', '#231000'],
  purple: ['#f6f2ff', '#e8daff', '#d4bbff', '#be95ff', '#a56eff', '#8a3ffc', '#6929c4', '#491d8b', '#31135e', '#1c0f30'],
  red: ['#fff1f1', '#ffd7d9', '#ffb3b8', '#ff8389', '#fa4d56', '#da1e28', '#a2191f', '#750e13', '#520408', '#2d0709'],
  teal: ['#d9fbfb', '#9ef0f0', '#3ddbd9', '#08bdba', '#009d9a', '#007d79', '#005d5d', '#004144', '#022b30', '#081a1c'],
  yellow: ['#fcf4d6', '#fddc69', '#f1c21b', '#d2a106', '#b28600', '#8e6a00', '#684e00', '#483700', '#302400', '#1c1500'],
}

/**
 * Depth-indexed token groups. `borderSubtle` has FOUR entries because depth 0
 * exists for it — an element sitting directly on the page rather than inside a
 * layer. Every other group starts at layer 01.
 */
export type CarbonLayerGroup = 'layer' | 'layerHover' | 'layerActive' | 'layerSelected' | 'field' | 'fieldHover' | 'borderSubtle' | 'borderStrong'

export type CarbonTheme = {
  flat: Record<string, string>
  layers: Record<CarbonLayerGroup, readonly string[]>
}

export const CARBON_THEMES: Record<string, CarbonTheme> = {
  white: {
    flat: {
      background: '#ffffff',
      backgroundHover: 'rgba(141, 141, 141, 0.12)',
      backgroundActive: 'rgba(141, 141, 141, 0.5)',
      backgroundInverse: '#393939',
      textPrimary: '#161616',
      textSecondary: '#525252',
      textPlaceholder: 'rgba(22, 22, 22, 0.4)',
      textHelper: '#6f6f6f',
      textOnColor: '#ffffff',
      textInverse: '#ffffff',
      textDisabled: 'rgba(22, 22, 22, 0.25)',
      textError: '#da1e28',
      linkPrimary: '#0f62fe',
      linkSecondary: '#0043ce',
      linkInverse: '#78a9ff',
      linkVisited: '#8a3ffc',
      iconPrimary: '#161616',
      iconSecondary: '#525252',
      iconOnColor: '#ffffff',
      iconInverse: '#ffffff',
      iconDisabled: 'rgba(22, 22, 22, 0.25)',
      interactive: '#0f62fe',
      focus: '#0f62fe',
      focusInverse: '#ffffff',
      highlight: '#d0e2ff',
      overlay: 'rgba(0, 0, 0, 0.6)',
      borderInteractive: '#0f62fe',
      borderInverse: '#161616',
      borderDisabled: '#c6c6c6',
      supportError: '#da1e28',
      supportSuccess: '#24a148',
      supportWarning: '#f1c21b',
      supportInfo: '#0043ce',
      supportErrorInverse: '#fa4d56',
      supportSuccessInverse: '#42be65',
      supportWarningInverse: '#f1c21b',
      supportInfoInverse: '#4589ff',
    },
    layers: {
      layer: ['#f4f4f4', '#ffffff', '#f4f4f4'],
      layerHover: ['#e8e8e8', '#e8e8e8', '#e8e8e8'],
      layerActive: ['#c6c6c6', '#c6c6c6', '#c6c6c6'],
      layerSelected: ['#e0e0e0', '#e0e0e0', '#e0e0e0'],
      field: ['#f4f4f4', '#ffffff', '#f4f4f4'],
      fieldHover: ['#e8e8e8', '#e8e8e8', '#e8e8e8'],
      borderSubtle: ['#e0e0e0', '#c6c6c6', '#e0e0e0', '#c6c6c6'],
      borderStrong: ['#8d8d8d', '#8d8d8d', '#8d8d8d'],
    },
  },
  g10: {
    flat: {
      background: '#f4f4f4',
      backgroundHover: 'rgba(141, 141, 141, 0.12)',
      backgroundActive: 'rgba(141, 141, 141, 0.5)',
      backgroundInverse: '#393939',
      textPrimary: '#161616',
      textSecondary: '#525252',
      textPlaceholder: 'rgba(22, 22, 22, 0.4)',
      textHelper: '#6f6f6f',
      textOnColor: '#ffffff',
      textInverse: '#ffffff',
      textDisabled: 'rgba(22, 22, 22, 0.25)',
      textError: '#da1e28',
      linkPrimary: '#0f62fe',
      linkSecondary: '#0043ce',
      linkInverse: '#78a9ff',
      linkVisited: '#8a3ffc',
      iconPrimary: '#161616',
      iconSecondary: '#525252',
      iconOnColor: '#ffffff',
      iconInverse: '#ffffff',
      iconDisabled: 'rgba(22, 22, 22, 0.25)',
      interactive: '#0f62fe',
      focus: '#0f62fe',
      focusInverse: '#ffffff',
      highlight: '#d0e2ff',
      overlay: 'rgba(0, 0, 0, 0.6)',
      borderInteractive: '#0f62fe',
      borderInverse: '#161616',
      borderDisabled: '#c6c6c6',
      supportError: '#da1e28',
      supportSuccess: '#24a148',
      supportWarning: '#f1c21b',
      supportInfo: '#0043ce',
      supportErrorInverse: '#fa4d56',
      supportSuccessInverse: '#42be65',
      supportWarningInverse: '#f1c21b',
      supportInfoInverse: '#4589ff',
    },
    layers: {
      layer: ['#ffffff', '#f4f4f4', '#ffffff'],
      layerHover: ['#e8e8e8', '#e8e8e8', '#e8e8e8'],
      layerActive: ['#c6c6c6', '#c6c6c6', '#c6c6c6'],
      layerSelected: ['#e0e0e0', '#e0e0e0', '#e0e0e0'],
      field: ['#ffffff', '#f4f4f4', '#ffffff'],
      fieldHover: ['#e8e8e8', '#e8e8e8', '#e8e8e8'],
      borderSubtle: ['#c6c6c6', '#e0e0e0', '#c6c6c6', '#e0e0e0'],
      borderStrong: ['#8d8d8d', '#8d8d8d', '#8d8d8d'],
    },
  },
  g90: {
    flat: {
      background: '#262626',
      backgroundHover: 'rgba(141, 141, 141, 0.16)',
      backgroundActive: 'rgba(141, 141, 141, 0.4)',
      backgroundInverse: '#f4f4f4',
      textPrimary: '#f4f4f4',
      textSecondary: '#c6c6c6',
      textPlaceholder: 'rgba(244, 244, 244, 0.4)',
      textHelper: '#c6c6c6',
      textOnColor: '#ffffff',
      textInverse: '#161616',
      textDisabled: 'rgba(244, 244, 244, 0.25)',
      textError: '#ffb3b8',
      linkPrimary: '#78a9ff',
      linkSecondary: '#a6c8ff',
      linkInverse: '#0f62fe',
      linkVisited: '#be95ff',
      iconPrimary: '#f4f4f4',
      iconSecondary: '#c6c6c6',
      iconOnColor: '#ffffff',
      iconInverse: '#161616',
      iconDisabled: 'rgba(244, 244, 244, 0.25)',
      interactive: '#4589ff',
      focus: '#ffffff',
      focusInverse: '#0f62fe',
      highlight: '#002d9c',
      overlay: 'rgba(0, 0, 0, 0.6)',
      borderInteractive: '#4589ff',
      borderInverse: '#f4f4f4',
      borderDisabled: 'rgba(141, 141, 141, 0.5)',
      supportError: '#ff8389',
      supportSuccess: '#42be65',
      supportWarning: '#f1c21b',
      supportInfo: '#4589ff',
      supportErrorInverse: '#da1e28',
      supportSuccessInverse: '#24a148',
      supportWarningInverse: '#f1c21b',
      supportInfoInverse: '#0043ce',
    },
    layers: {
      layer: ['#393939', '#525252', '#6f6f6f'],
      layerHover: ['#474747', '#636363', '#5e5e5e'],
      layerActive: ['#6f6f6f', '#8d8d8d', '#393939'],
      layerSelected: ['#525252', '#6f6f6f', '#525252'],
      field: ['#393939', '#525252', '#6f6f6f'],
      fieldHover: ['#474747', '#636363', '#5e5e5e'],
      borderSubtle: ['#525252', '#6f6f6f', '#8d8d8d', '#8d8d8d'],
      borderStrong: ['#8d8d8d', '#a8a8a8', '#c6c6c6'],
    },
  },
  g100: {
    flat: {
      background: '#161616',
      backgroundHover: 'rgba(141, 141, 141, 0.16)',
      backgroundActive: 'rgba(141, 141, 141, 0.4)',
      backgroundInverse: '#f4f4f4',
      textPrimary: '#f4f4f4',
      textSecondary: '#c6c6c6',
      textPlaceholder: 'rgba(244, 244, 244, 0.4)',
      textHelper: '#a8a8a8',
      textOnColor: '#ffffff',
      textInverse: '#161616',
      textDisabled: 'rgba(244, 244, 244, 0.25)',
      textError: '#ff8389',
      linkPrimary: '#78a9ff',
      linkSecondary: '#a6c8ff',
      linkInverse: '#0f62fe',
      linkVisited: '#be95ff',
      iconPrimary: '#f4f4f4',
      iconSecondary: '#c6c6c6',
      iconOnColor: '#ffffff',
      iconInverse: '#161616',
      iconDisabled: 'rgba(244, 244, 244, 0.25)',
      interactive: '#4589ff',
      focus: '#ffffff',
      focusInverse: '#0f62fe',
      highlight: '#001d6c',
      overlay: 'rgba(0, 0, 0, 0.6)',
      borderInteractive: '#4589ff',
      borderInverse: '#f4f4f4',
      borderDisabled: 'rgba(141, 141, 141, 0.5)',
      supportError: '#fa4d56',
      supportSuccess: '#42be65',
      supportWarning: '#f1c21b',
      supportInfo: '#4589ff',
      supportErrorInverse: '#da1e28',
      supportSuccessInverse: '#24a148',
      supportWarningInverse: '#f1c21b',
      supportInfoInverse: '#0043ce',
    },
    layers: {
      layer: ['#262626', '#393939', '#525252'],
      layerHover: ['#333333', '#474747', '#636363'],
      layerActive: ['#525252', '#6f6f6f', '#8d8d8d'],
      layerSelected: ['#393939', '#525252', '#6f6f6f'],
      field: ['#262626', '#393939', '#525252'],
      fieldHover: ['#333333', '#474747', '#636363'],
      borderSubtle: ['#393939', '#525252', '#6f6f6f', '#6f6f6f'],
      borderStrong: ['#6f6f6f', '#8d8d8d', '#a8a8a8'],
    },
  },
}

/**
 * One core UI token in one theme, as the palette position IBM picked.
 *
 * `exact: false` means IBM's value is NOT a literal palette entry — an
 * off-ladder hover hex, or an `rgba()` composited over that theme's
 * `layer01` — and `family`/`stop` is the nearest stop to its effective
 * colour. `raw` keeps IBM's literal value so the snap stays checkable.
 */
export type CarbonStopRef = {
  family: string
  stop: number
  exact: boolean
  raw: string
}

/** How many core UI tokens each theme carries. Asserted by the test suite. */
export const CARBON_CORE_TOKEN_COUNT = 103

/**
 * `theme → kebab token name → stop`. THIS is what the semantic architecture
 * is generated from: the token list and the per-theme stop are IBM's, and the
 * only thing Escala adds is a stop → ramp-tone mapping.
 */
export const CARBON_TOKENS: Record<string, Record<string, CarbonStopRef>> = {
  white: {
    'background': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'background-active': { family: 'gray', stop: 30, exact: false, raw: 'rgba(141, 141, 141, 0.5)' },
    'background-brand': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'background-hover': { family: 'gray', stop: 20, exact: false, raw: 'rgba(141, 141, 141, 0.12)' },
    'background-inverse': { family: 'gray', stop: 80, exact: true, raw: '#393939' },
    'background-inverse-hover': { family: 'gray', stop: 70, exact: false, raw: '#474747' },
    'background-selected': { family: 'gray', stop: 20, exact: false, raw: 'rgba(141, 141, 141, 0.2)' },
    'background-selected-hover': { family: 'gray', stop: 20, exact: false, raw: 'rgba(141, 141, 141, 0.32)' },
    'border-disabled': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'border-interactive': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'border-inverse': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'border-strong-01': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'border-strong-02': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'border-strong-03': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'border-subtle-00': { family: 'gray', stop: 20, exact: true, raw: '#e0e0e0' },
    'border-subtle-01': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'border-subtle-02': { family: 'gray', stop: 20, exact: true, raw: '#e0e0e0' },
    'border-subtle-03': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'border-subtle-selected-01': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'border-subtle-selected-02': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'border-subtle-selected-03': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'border-tile-01': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'border-tile-02': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'border-tile-03': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'field-01': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'field-02': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'field-03': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'field-hover-01': { family: 'gray', stop: 20, exact: false, raw: '#e8e8e8' },
    'field-hover-02': { family: 'gray', stop: 20, exact: false, raw: '#e8e8e8' },
    'field-hover-03': { family: 'gray', stop: 20, exact: false, raw: '#e8e8e8' },
    'focus': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'focus-inset': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'focus-inverse': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'highlight': { family: 'blue', stop: 20, exact: true, raw: '#d0e2ff' },
    'icon-disabled': { family: 'gray', stop: 30, exact: false, raw: 'rgba(22, 22, 22, 0.25)' },
    'icon-interactive': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'icon-inverse': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'icon-on-color': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'icon-on-color-disabled': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'icon-primary': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'icon-secondary': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'interactive': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'layer-01': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'layer-02': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'layer-03': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'layer-accent-01': { family: 'gray', stop: 20, exact: true, raw: '#e0e0e0' },
    'layer-accent-02': { family: 'gray', stop: 20, exact: true, raw: '#e0e0e0' },
    'layer-accent-03': { family: 'gray', stop: 20, exact: true, raw: '#e0e0e0' },
    'layer-accent-active-01': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'layer-accent-active-02': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'layer-accent-active-03': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'layer-accent-hover-01': { family: 'gray', stop: 30, exact: false, raw: '#d1d1d1' },
    'layer-accent-hover-02': { family: 'gray', stop: 30, exact: false, raw: '#d1d1d1' },
    'layer-accent-hover-03': { family: 'gray', stop: 30, exact: false, raw: '#d1d1d1' },
    'layer-active-01': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'layer-active-02': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'layer-active-03': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'layer-background-01': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'layer-background-02': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'layer-background-03': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'layer-hover-01': { family: 'gray', stop: 20, exact: false, raw: '#e8e8e8' },
    'layer-hover-02': { family: 'gray', stop: 20, exact: false, raw: '#e8e8e8' },
    'layer-hover-03': { family: 'gray', stop: 20, exact: false, raw: '#e8e8e8' },
    'layer-selected-01': { family: 'gray', stop: 20, exact: true, raw: '#e0e0e0' },
    'layer-selected-02': { family: 'gray', stop: 20, exact: true, raw: '#e0e0e0' },
    'layer-selected-03': { family: 'gray', stop: 20, exact: true, raw: '#e0e0e0' },
    'layer-selected-disabled': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'layer-selected-hover-01': { family: 'gray', stop: 30, exact: false, raw: '#d1d1d1' },
    'layer-selected-hover-02': { family: 'gray', stop: 30, exact: false, raw: '#d1d1d1' },
    'layer-selected-hover-03': { family: 'gray', stop: 30, exact: false, raw: '#d1d1d1' },
    'layer-selected-inverse': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'link-inverse': { family: 'blue', stop: 40, exact: true, raw: '#78a9ff' },
    'link-inverse-active': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'link-inverse-hover': { family: 'blue', stop: 30, exact: true, raw: '#a6c8ff' },
    'link-inverse-visited': { family: 'purple', stop: 40, exact: true, raw: '#be95ff' },
    'link-primary': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'link-primary-hover': { family: 'blue', stop: 70, exact: true, raw: '#0043ce' },
    'link-secondary': { family: 'blue', stop: 70, exact: true, raw: '#0043ce' },
    'link-visited': { family: 'purple', stop: 60, exact: true, raw: '#8a3ffc' },
    'overlay': { family: 'gray', stop: 60, exact: false, raw: 'rgba(0, 0, 0, 0.6)' },
    'skeleton-background': { family: 'gray', stop: 20, exact: false, raw: '#e8e8e8' },
    'skeleton-element': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'support-caution-major': { family: 'orange', stop: 40, exact: true, raw: '#ff832b' },
    'support-caution-minor': { family: 'yellow', stop: 30, exact: true, raw: '#f1c21b' },
    'support-caution-undefined': { family: 'purple', stop: 60, exact: true, raw: '#8a3ffc' },
    'support-error': { family: 'red', stop: 60, exact: true, raw: '#da1e28' },
    'support-error-inverse': { family: 'red', stop: 50, exact: true, raw: '#fa4d56' },
    'support-info': { family: 'blue', stop: 70, exact: true, raw: '#0043ce' },
    'support-info-inverse': { family: 'blue', stop: 50, exact: true, raw: '#4589ff' },
    'support-success': { family: 'green', stop: 50, exact: true, raw: '#24a148' },
    'support-success-inverse': { family: 'green', stop: 40, exact: true, raw: '#42be65' },
    'support-warning': { family: 'yellow', stop: 30, exact: true, raw: '#f1c21b' },
    'support-warning-inverse': { family: 'yellow', stop: 30, exact: true, raw: '#f1c21b' },
    'text-disabled': { family: 'gray', stop: 30, exact: false, raw: 'rgba(22, 22, 22, 0.25)' },
    'text-error': { family: 'red', stop: 60, exact: true, raw: '#da1e28' },
    'text-helper': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'text-inverse': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'text-on-color': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'text-on-color-disabled': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'text-placeholder': { family: 'gray', stop: 40, exact: false, raw: 'rgba(22, 22, 22, 0.4)' },
    'text-primary': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'text-secondary': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'toggle-off': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
  },
  g10: {
    'background': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'background-active': { family: 'gray', stop: 30, exact: false, raw: 'rgba(141, 141, 141, 0.5)' },
    'background-brand': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'background-hover': { family: 'gray', stop: 10, exact: false, raw: 'rgba(141, 141, 141, 0.12)' },
    'background-inverse': { family: 'gray', stop: 80, exact: true, raw: '#393939' },
    'background-inverse-hover': { family: 'gray', stop: 70, exact: false, raw: '#474747' },
    'background-selected': { family: 'gray', stop: 20, exact: false, raw: 'rgba(141, 141, 141, 0.2)' },
    'background-selected-hover': { family: 'gray', stop: 20, exact: false, raw: 'rgba(141, 141, 141, 0.32)' },
    'border-disabled': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'border-interactive': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'border-inverse': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'border-strong-01': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'border-strong-02': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'border-strong-03': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'border-subtle-00': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'border-subtle-01': { family: 'gray', stop: 20, exact: true, raw: '#e0e0e0' },
    'border-subtle-02': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'border-subtle-03': { family: 'gray', stop: 20, exact: true, raw: '#e0e0e0' },
    'border-subtle-selected-01': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'border-subtle-selected-02': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'border-subtle-selected-03': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'border-tile-01': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'border-tile-02': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'border-tile-03': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'field-01': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'field-02': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'field-03': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'field-hover-01': { family: 'gray', stop: 20, exact: false, raw: '#e8e8e8' },
    'field-hover-02': { family: 'gray', stop: 20, exact: false, raw: '#e8e8e8' },
    'field-hover-03': { family: 'gray', stop: 20, exact: false, raw: '#e8e8e8' },
    'focus': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'focus-inset': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'focus-inverse': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'highlight': { family: 'blue', stop: 20, exact: true, raw: '#d0e2ff' },
    'icon-disabled': { family: 'gray', stop: 30, exact: false, raw: 'rgba(22, 22, 22, 0.25)' },
    'icon-interactive': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'icon-inverse': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'icon-on-color': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'icon-on-color-disabled': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'icon-primary': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'icon-secondary': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'interactive': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'layer-01': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'layer-02': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'layer-03': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'layer-accent-01': { family: 'gray', stop: 20, exact: true, raw: '#e0e0e0' },
    'layer-accent-02': { family: 'gray', stop: 20, exact: true, raw: '#e0e0e0' },
    'layer-accent-03': { family: 'gray', stop: 20, exact: true, raw: '#e0e0e0' },
    'layer-accent-active-01': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'layer-accent-active-02': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'layer-accent-active-03': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'layer-accent-hover-01': { family: 'gray', stop: 30, exact: false, raw: '#d1d1d1' },
    'layer-accent-hover-02': { family: 'gray', stop: 30, exact: false, raw: '#d1d1d1' },
    'layer-accent-hover-03': { family: 'gray', stop: 30, exact: false, raw: '#d1d1d1' },
    'layer-active-01': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'layer-active-02': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'layer-active-03': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'layer-background-01': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'layer-background-02': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'layer-background-03': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'layer-hover-01': { family: 'gray', stop: 20, exact: false, raw: '#e8e8e8' },
    'layer-hover-02': { family: 'gray', stop: 20, exact: false, raw: '#e8e8e8' },
    'layer-hover-03': { family: 'gray', stop: 20, exact: false, raw: '#e8e8e8' },
    'layer-selected-01': { family: 'gray', stop: 20, exact: true, raw: '#e0e0e0' },
    'layer-selected-02': { family: 'gray', stop: 20, exact: true, raw: '#e0e0e0' },
    'layer-selected-03': { family: 'gray', stop: 20, exact: true, raw: '#e0e0e0' },
    'layer-selected-disabled': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'layer-selected-hover-01': { family: 'gray', stop: 30, exact: false, raw: '#d1d1d1' },
    'layer-selected-hover-02': { family: 'gray', stop: 30, exact: false, raw: '#d1d1d1' },
    'layer-selected-hover-03': { family: 'gray', stop: 30, exact: false, raw: '#d1d1d1' },
    'layer-selected-inverse': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'link-inverse': { family: 'blue', stop: 40, exact: true, raw: '#78a9ff' },
    'link-inverse-active': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'link-inverse-hover': { family: 'blue', stop: 30, exact: true, raw: '#a6c8ff' },
    'link-inverse-visited': { family: 'purple', stop: 40, exact: true, raw: '#be95ff' },
    'link-primary': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'link-primary-hover': { family: 'blue', stop: 70, exact: true, raw: '#0043ce' },
    'link-secondary': { family: 'blue', stop: 70, exact: true, raw: '#0043ce' },
    'link-visited': { family: 'purple', stop: 60, exact: true, raw: '#8a3ffc' },
    'overlay': { family: 'gray', stop: 60, exact: false, raw: 'rgba(0, 0, 0, 0.6)' },
    'skeleton-background': { family: 'gray', stop: 20, exact: false, raw: '#e8e8e8' },
    'skeleton-element': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'support-caution-major': { family: 'orange', stop: 40, exact: true, raw: '#ff832b' },
    'support-caution-minor': { family: 'yellow', stop: 30, exact: true, raw: '#f1c21b' },
    'support-caution-undefined': { family: 'purple', stop: 60, exact: true, raw: '#8a3ffc' },
    'support-error': { family: 'red', stop: 60, exact: true, raw: '#da1e28' },
    'support-error-inverse': { family: 'red', stop: 50, exact: true, raw: '#fa4d56' },
    'support-info': { family: 'blue', stop: 70, exact: true, raw: '#0043ce' },
    'support-info-inverse': { family: 'blue', stop: 50, exact: true, raw: '#4589ff' },
    'support-success': { family: 'green', stop: 50, exact: true, raw: '#24a148' },
    'support-success-inverse': { family: 'green', stop: 40, exact: true, raw: '#42be65' },
    'support-warning': { family: 'yellow', stop: 30, exact: true, raw: '#f1c21b' },
    'support-warning-inverse': { family: 'yellow', stop: 30, exact: true, raw: '#f1c21b' },
    'text-disabled': { family: 'gray', stop: 30, exact: false, raw: 'rgba(22, 22, 22, 0.25)' },
    'text-error': { family: 'red', stop: 60, exact: true, raw: '#da1e28' },
    'text-helper': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'text-inverse': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'text-on-color': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'text-on-color-disabled': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'text-placeholder': { family: 'gray', stop: 40, exact: false, raw: 'rgba(22, 22, 22, 0.4)' },
    'text-primary': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'text-secondary': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'toggle-off': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
  },
  g90: {
    'background': { family: 'gray', stop: 90, exact: true, raw: '#262626' },
    'background-active': { family: 'gray', stop: 70, exact: false, raw: 'rgba(141, 141, 141, 0.4)' },
    'background-brand': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'background-hover': { family: 'gray', stop: 70, exact: false, raw: 'rgba(141, 141, 141, 0.16)' },
    'background-inverse': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'background-inverse-hover': { family: 'gray', stop: 20, exact: false, raw: '#e8e8e8' },
    'background-selected': { family: 'gray', stop: 70, exact: false, raw: 'rgba(141, 141, 141, 0.24)' },
    'background-selected-hover': { family: 'gray', stop: 70, exact: false, raw: 'rgba(141, 141, 141, 0.32)' },
    'border-disabled': { family: 'gray', stop: 60, exact: false, raw: 'rgba(141, 141, 141, 0.5)' },
    'border-interactive': { family: 'blue', stop: 50, exact: true, raw: '#4589ff' },
    'border-inverse': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'border-strong-01': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'border-strong-02': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'border-strong-03': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'border-subtle-00': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'border-subtle-01': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'border-subtle-02': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'border-subtle-03': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'border-subtle-selected-01': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'border-subtle-selected-02': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'border-subtle-selected-03': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'border-tile-01': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'border-tile-02': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'border-tile-03': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'field-01': { family: 'gray', stop: 80, exact: true, raw: '#393939' },
    'field-02': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'field-03': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'field-hover-01': { family: 'gray', stop: 70, exact: false, raw: '#474747' },
    'field-hover-02': { family: 'gray', stop: 60, exact: false, raw: '#636363' },
    'field-hover-03': { family: 'gray', stop: 70, exact: false, raw: '#5e5e5e' },
    'focus': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'focus-inset': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'focus-inverse': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'highlight': { family: 'blue', stop: 80, exact: true, raw: '#002d9c' },
    'icon-disabled': { family: 'gray', stop: 60, exact: false, raw: 'rgba(244, 244, 244, 0.25)' },
    'icon-interactive': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'icon-inverse': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'icon-on-color': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'icon-on-color-disabled': { family: 'gray', stop: 60, exact: false, raw: 'rgba(255, 255, 255, 0.25)' },
    'icon-primary': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'icon-secondary': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'interactive': { family: 'blue', stop: 50, exact: true, raw: '#4589ff' },
    'layer-01': { family: 'gray', stop: 80, exact: true, raw: '#393939' },
    'layer-02': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'layer-03': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'layer-accent-01': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'layer-accent-02': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'layer-accent-03': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'layer-accent-active-01': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'layer-accent-active-02': { family: 'gray', stop: 80, exact: true, raw: '#393939' },
    'layer-accent-active-03': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'layer-accent-hover-01': { family: 'gray', stop: 60, exact: false, raw: '#636363' },
    'layer-accent-hover-02': { family: 'gray', stop: 70, exact: false, raw: '#5e5e5e' },
    'layer-accent-hover-03': { family: 'gray', stop: 60, exact: false, raw: '#7a7a7a' },
    'layer-active-01': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'layer-active-02': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'layer-active-03': { family: 'gray', stop: 80, exact: true, raw: '#393939' },
    'layer-background-01': { family: 'gray', stop: 90, exact: true, raw: '#262626' },
    'layer-background-02': { family: 'gray', stop: 80, exact: true, raw: '#393939' },
    'layer-background-03': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'layer-hover-01': { family: 'gray', stop: 70, exact: false, raw: '#474747' },
    'layer-hover-02': { family: 'gray', stop: 60, exact: false, raw: '#636363' },
    'layer-hover-03': { family: 'gray', stop: 70, exact: false, raw: '#5e5e5e' },
    'layer-selected-01': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'layer-selected-02': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'layer-selected-03': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'layer-selected-disabled': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'layer-selected-hover-01': { family: 'gray', stop: 60, exact: false, raw: '#636363' },
    'layer-selected-hover-02': { family: 'gray', stop: 70, exact: false, raw: '#5e5e5e' },
    'layer-selected-hover-03': { family: 'gray', stop: 60, exact: false, raw: '#636363' },
    'layer-selected-inverse': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'link-inverse': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'link-inverse-active': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'link-inverse-hover': { family: 'blue', stop: 70, exact: true, raw: '#0043ce' },
    'link-inverse-visited': { family: 'purple', stop: 60, exact: true, raw: '#8a3ffc' },
    'link-primary': { family: 'blue', stop: 40, exact: true, raw: '#78a9ff' },
    'link-primary-hover': { family: 'blue', stop: 30, exact: true, raw: '#a6c8ff' },
    'link-secondary': { family: 'blue', stop: 30, exact: true, raw: '#a6c8ff' },
    'link-visited': { family: 'purple', stop: 40, exact: true, raw: '#be95ff' },
    'overlay': { family: 'gray', stop: 100, exact: false, raw: 'rgba(0, 0, 0, 0.6)' },
    'skeleton-background': { family: 'gray', stop: 80, exact: false, raw: '#333333' },
    'skeleton-element': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'support-caution-major': { family: 'orange', stop: 40, exact: true, raw: '#ff832b' },
    'support-caution-minor': { family: 'yellow', stop: 30, exact: true, raw: '#f1c21b' },
    'support-caution-undefined': { family: 'purple', stop: 50, exact: true, raw: '#a56eff' },
    'support-error': { family: 'red', stop: 40, exact: true, raw: '#ff8389' },
    'support-error-inverse': { family: 'red', stop: 60, exact: true, raw: '#da1e28' },
    'support-info': { family: 'blue', stop: 50, exact: true, raw: '#4589ff' },
    'support-info-inverse': { family: 'blue', stop: 70, exact: true, raw: '#0043ce' },
    'support-success': { family: 'green', stop: 40, exact: true, raw: '#42be65' },
    'support-success-inverse': { family: 'green', stop: 50, exact: true, raw: '#24a148' },
    'support-warning': { family: 'yellow', stop: 30, exact: true, raw: '#f1c21b' },
    'support-warning-inverse': { family: 'yellow', stop: 30, exact: true, raw: '#f1c21b' },
    'text-disabled': { family: 'gray', stop: 60, exact: false, raw: 'rgba(244, 244, 244, 0.25)' },
    'text-error': { family: 'red', stop: 30, exact: true, raw: '#ffb3b8' },
    'text-helper': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'text-inverse': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'text-on-color': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'text-on-color-disabled': { family: 'gray', stop: 60, exact: false, raw: 'rgba(255, 255, 255, 0.25)' },
    'text-placeholder': { family: 'gray', stop: 50, exact: false, raw: 'rgba(244, 244, 244, 0.4)' },
    'text-primary': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'text-secondary': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'toggle-off': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
  },
  g100: {
    'background': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'background-active': { family: 'gray', stop: 70, exact: false, raw: 'rgba(141, 141, 141, 0.4)' },
    'background-brand': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'background-hover': { family: 'gray', stop: 80, exact: false, raw: 'rgba(141, 141, 141, 0.16)' },
    'background-inverse': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'background-inverse-hover': { family: 'gray', stop: 20, exact: false, raw: '#e8e8e8' },
    'background-selected': { family: 'gray', stop: 80, exact: false, raw: 'rgba(141, 141, 141, 0.24)' },
    'background-selected-hover': { family: 'gray', stop: 70, exact: false, raw: 'rgba(141, 141, 141, 0.32)' },
    'border-disabled': { family: 'gray', stop: 70, exact: false, raw: 'rgba(141, 141, 141, 0.5)' },
    'border-interactive': { family: 'blue', stop: 50, exact: true, raw: '#4589ff' },
    'border-inverse': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'border-strong-01': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'border-strong-02': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'border-strong-03': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'border-subtle-00': { family: 'gray', stop: 80, exact: true, raw: '#393939' },
    'border-subtle-01': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'border-subtle-02': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'border-subtle-03': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'border-subtle-selected-01': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'border-subtle-selected-02': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'border-subtle-selected-03': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'border-tile-01': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'border-tile-02': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'border-tile-03': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'field-01': { family: 'gray', stop: 90, exact: true, raw: '#262626' },
    'field-02': { family: 'gray', stop: 80, exact: true, raw: '#393939' },
    'field-03': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'field-hover-01': { family: 'gray', stop: 80, exact: false, raw: '#333333' },
    'field-hover-02': { family: 'gray', stop: 70, exact: false, raw: '#474747' },
    'field-hover-03': { family: 'gray', stop: 60, exact: false, raw: '#636363' },
    'focus': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'focus-inset': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'focus-inverse': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'highlight': { family: 'blue', stop: 90, exact: true, raw: '#001d6c' },
    'icon-disabled': { family: 'gray', stop: 70, exact: false, raw: 'rgba(244, 244, 244, 0.25)' },
    'icon-interactive': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'icon-inverse': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'icon-on-color': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'icon-on-color-disabled': { family: 'gray', stop: 70, exact: false, raw: 'rgba(255, 255, 255, 0.25)' },
    'icon-primary': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'icon-secondary': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'interactive': { family: 'blue', stop: 50, exact: true, raw: '#4589ff' },
    'layer-01': { family: 'gray', stop: 90, exact: true, raw: '#262626' },
    'layer-02': { family: 'gray', stop: 80, exact: true, raw: '#393939' },
    'layer-03': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'layer-accent-01': { family: 'gray', stop: 80, exact: true, raw: '#393939' },
    'layer-accent-02': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'layer-accent-03': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'layer-accent-active-01': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'layer-accent-active-02': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'layer-accent-active-03': { family: 'gray', stop: 80, exact: true, raw: '#393939' },
    'layer-accent-hover-01': { family: 'gray', stop: 70, exact: false, raw: '#474747' },
    'layer-accent-hover-02': { family: 'gray', stop: 60, exact: false, raw: '#636363' },
    'layer-accent-hover-03': { family: 'gray', stop: 70, exact: false, raw: '#5e5e5e' },
    'layer-active-01': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'layer-active-02': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'layer-active-03': { family: 'gray', stop: 50, exact: true, raw: '#8d8d8d' },
    'layer-background-01': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'layer-background-02': { family: 'gray', stop: 90, exact: true, raw: '#262626' },
    'layer-background-03': { family: 'gray', stop: 80, exact: true, raw: '#393939' },
    'layer-hover-01': { family: 'gray', stop: 80, exact: false, raw: '#333333' },
    'layer-hover-02': { family: 'gray', stop: 70, exact: false, raw: '#474747' },
    'layer-hover-03': { family: 'gray', stop: 60, exact: false, raw: '#636363' },
    'layer-selected-01': { family: 'gray', stop: 80, exact: true, raw: '#393939' },
    'layer-selected-02': { family: 'gray', stop: 70, exact: true, raw: '#525252' },
    'layer-selected-03': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
    'layer-selected-disabled': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'layer-selected-hover-01': { family: 'gray', stop: 70, exact: false, raw: '#474747' },
    'layer-selected-hover-02': { family: 'gray', stop: 60, exact: false, raw: '#636363' },
    'layer-selected-hover-03': { family: 'gray', stop: 70, exact: false, raw: '#5e5e5e' },
    'layer-selected-inverse': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'link-inverse': { family: 'blue', stop: 60, exact: true, raw: '#0f62fe' },
    'link-inverse-active': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'link-inverse-hover': { family: 'blue', stop: 70, exact: true, raw: '#0043ce' },
    'link-inverse-visited': { family: 'purple', stop: 60, exact: true, raw: '#8a3ffc' },
    'link-primary': { family: 'blue', stop: 40, exact: true, raw: '#78a9ff' },
    'link-primary-hover': { family: 'blue', stop: 30, exact: true, raw: '#a6c8ff' },
    'link-secondary': { family: 'blue', stop: 30, exact: true, raw: '#a6c8ff' },
    'link-visited': { family: 'purple', stop: 40, exact: true, raw: '#be95ff' },
    'overlay': { family: 'gray', stop: 100, exact: false, raw: 'rgba(0, 0, 0, 0.6)' },
    'skeleton-background': { family: 'gray', stop: 90, exact: false, raw: '#292929' },
    'skeleton-element': { family: 'gray', stop: 80, exact: true, raw: '#393939' },
    'support-caution-major': { family: 'orange', stop: 40, exact: true, raw: '#ff832b' },
    'support-caution-minor': { family: 'yellow', stop: 30, exact: true, raw: '#f1c21b' },
    'support-caution-undefined': { family: 'purple', stop: 50, exact: true, raw: '#a56eff' },
    'support-error': { family: 'red', stop: 50, exact: true, raw: '#fa4d56' },
    'support-error-inverse': { family: 'red', stop: 60, exact: true, raw: '#da1e28' },
    'support-info': { family: 'blue', stop: 50, exact: true, raw: '#4589ff' },
    'support-info-inverse': { family: 'blue', stop: 70, exact: true, raw: '#0043ce' },
    'support-success': { family: 'green', stop: 40, exact: true, raw: '#42be65' },
    'support-success-inverse': { family: 'green', stop: 50, exact: true, raw: '#24a148' },
    'support-warning': { family: 'yellow', stop: 30, exact: true, raw: '#f1c21b' },
    'support-warning-inverse': { family: 'yellow', stop: 30, exact: true, raw: '#f1c21b' },
    'text-disabled': { family: 'gray', stop: 70, exact: false, raw: 'rgba(244, 244, 244, 0.25)' },
    'text-error': { family: 'red', stop: 40, exact: true, raw: '#ff8389' },
    'text-helper': { family: 'gray', stop: 40, exact: true, raw: '#a8a8a8' },
    'text-inverse': { family: 'gray', stop: 100, exact: true, raw: '#161616' },
    'text-on-color': { family: 'white', stop: 0, exact: true, raw: '#ffffff' },
    'text-on-color-disabled': { family: 'gray', stop: 70, exact: false, raw: 'rgba(255, 255, 255, 0.25)' },
    'text-placeholder': { family: 'gray', stop: 60, exact: false, raw: 'rgba(244, 244, 244, 0.4)' },
    'text-primary': { family: 'gray', stop: 10, exact: true, raw: '#f4f4f4' },
    'text-secondary': { family: 'gray', stop: 30, exact: true, raw: '#c6c6c6' },
    'toggle-off': { family: 'gray', stop: 60, exact: true, raw: '#6f6f6f' },
  },
}
